# Generated by Django 5.2.6 on 2025-11-26 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jcpemobile', '0012_noticia_subtitulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemLinhaDoTempo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_linha_tempo', to='jcpemobile.noticia')),
            ],
            options={
                'verbose_name': 'Item da Linha do Tempo',
                'verbose_name_plural': 'Itens da Linha do Tempo',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='LinhaDoTempo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('noticia_principal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='linha_tempo', to='jcpemobile.noticia', verbose_name='Notícia Principal')),
                ('noticias_relacionadas', models.ManyToManyField(related_name='em_linhas_tempo', through='jcpemobile.ItemLinhaDoTempo', to='jcpemobile.noticia', verbose_name='Notícias Relacionadas')),
            ],
            options={
                'verbose_name': 'Linha do Tempo',
                'verbose_name_plural': 'Linhas do Tempo',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='itemlinhadotempo',
            name='linha_tempo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='jcpemobile.linhadotempo'),
        ),
        migrations.AlterUniqueTogether(
            name='itemlinhadotempo',
            unique_together={('linha_tempo', 'noticia')},
        ),
    ]
