# Generated by Django 5.2.6 on 2025-11-26 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jcpemobile', '0013_itemlinhadotempo_linhadotempo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linhadotempo',
            name='noticias_relacionadas',
        ),
        migrations.RemoveField(
            model_name='linhadotempo',
            name='noticia_principal',
        ),
        migrations.CreateModel(
            name='NoticiaLinhaDoTempo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Ordem em que a notícia aparece na linha do tempo (menor número aparece primeiro)', verbose_name='Ordem de Exibição')),
                ('ativa', models.BooleanField(default=True, help_text='Se marcado, a notícia aparecerá na linha do tempo', verbose_name='Ativa')),
                ('adicionada_em', models.DateTimeField(auto_now_add=True, verbose_name='Adicionada em')),
                ('atualizada_em', models.DateTimeField(auto_now=True, verbose_name='Atualizada em')),
                ('noticia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='na_linha_tempo', to='jcpemobile.noticia', verbose_name='Notícia')),
            ],
            options={
                'verbose_name': 'Notícia na Linha do Tempo',
                'verbose_name_plural': 'Notícias na Linha do Tempo',
                'ordering': ['ordem', '-adicionada_em'],
            },
        ),
        migrations.DeleteModel(
            name='ItemLinhaDoTempo',
        ),
        migrations.DeleteModel(
            name='LinhaDoTempo',
        ),
    ]
