# Generated by Django 5.2.6 on 2025-11-27 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jcpemobile', '0014_remove_linhadotempo_noticias_relacionadas_and_more'),
    ]

    operations = [
        # Deletar o modelo antigo NoticiaLinhaDoTempo da migração 0014
        migrations.DeleteModel(
            name='NoticiaLinhaDoTempo',
        ),
        # Criar modelo LinhaDoTempo
        migrations.CreateModel(
            name='LinhaDoTempo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text="Título da linha do tempo (ex: 'Eleições 2024', 'Copa do Mundo 2026')", max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('descricao', models.TextField(blank=True, help_text='Descrição breve sobre o tema desta linha do tempo', null=True, verbose_name='Descrição')),
                ('ativa', models.BooleanField(default=True, help_text='Se desmarcado, a linha do tempo não será exibida', verbose_name='Ativa')),
                ('criada_em', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('atualizada_em', models.DateTimeField(auto_now=True, verbose_name='Atualizada em')),
            ],
            options={
                'verbose_name': 'Linha do Tempo',
                'verbose_name_plural': 'Linhas do Tempo',
                'ordering': ['-criada_em'],
            },
        ),
        # Criar modelo NoticiaLinhaDoTempo
        migrations.CreateModel(
            name='NoticiaLinhaDoTempo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Ordem de exibição (deixe 0 para ordenar automaticamente por data)', verbose_name='Ordem')),
                ('adicionada_em', models.DateTimeField(auto_now_add=True, verbose_name='Adicionada em')),
                ('linha_tempo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noticias', to='jcpemobile.linhadotempo', verbose_name='Linha do Tempo')),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linhas_tempo', to='jcpemobile.noticia', verbose_name='Notícia')),
            ],
            options={
                'verbose_name': 'Notícia na Linha do Tempo',
                'verbose_name_plural': 'Notícias na Linha do Tempo',
                'ordering': ['linha_tempo', 'ordem', '-noticia__data_publicacao'],
                'unique_together': {('linha_tempo', 'noticia')},
            },
        ),
    ]
