# Generated by Django 5.2.6 on 2025-12-03 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jcpemobile', '0015_adicionar_linhas_do_tempo'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='imagem_vertical',
            field=models.ImageField(blank=True, help_text='Imagem vertical para exibição na aba Neels (proporção 9:16)', null=True, upload_to='noticias/vertical/', verbose_name='Imagem Vertical (Neels)'),
        ),
    ]
