# Generated by Django 5.2.6 on 2025-12-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jcpemobile', '0016_noticia_imagem_vertical'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticialinhadotempo',
            name='ativa',
            field=models.BooleanField(default=True, help_text='Indica se a notícia está ativa na linha do tempo', verbose_name='Ativa'),
        ),
        migrations.AddField(
            model_name='noticialinhadotempo',
            name='atualizada_em',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizada em'),
        ),
    ]
